image: harbor.eds.aphp.fr/public/python:3.8-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - pages
  - package

Linting:
  stage: test
  cache:
    - key:
        files:
          - .pre-commit-config.yaml
      paths:
        - ~/.pre-commit
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libfontconfig1-dev libfreetype6-dev build-essential cmake git
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  only:
    refs:
      - master
      - merge_request

Running Pytest:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libfontconfig1-dev libfreetype6-dev build-essential cmake
    - pip install -e '.[dev]'
  script:
    - pytest tests --cov edspdf_poppler --junitxml=report.xml
  after_script:
    - coverage xml -o coverage.xml
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    paths:
      - coverage.xml
      - report.xml
      - ./
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

  only:
    refs:
      - master
      - merge_request

Installation:
  stage: test
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends libfontconfig1-dev libfreetype6-dev build-essential cmake
    - pip install .
  only:
    refs:
      - master
      - merge_request

Test documentation:
  stage: test
  before_script:
    - pip install -r requirements-docs.txt
  script:
    - mkdocs build --site-dir documentation
  artifacts:
    paths:
      - documentation
  only:
    refs:
      - merge_request

pages:
  stage: pages
  before_script:
    - pip install .
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - master

Package:
  stage: package
  before_script:
    - apt-get update -y; apt-get install git -y;
    - pip install --upgrade pip; pip install twine build;
    - export LAST_RELEASE=`git ls-remote --tags --refs --sort="v:refname" $CI_PROJECT_URL.git | tail -n1 | sed 's/.*\///'`
    - echo $LAST_RELEASE
  script:
    - python -m build --sdist
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi/ -u gitlab-ci-token -p ${CI_JOB_TOKEN} dist/*
  only:
    - tags
