name: Documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Manually clone repository with submodules
        run: |
          git clone --recurse-submodules https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref }}

      - uses: actions/setup-python@v2

      - name: Set PY variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -e '.[docs]'

      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Build documentation
        run: |
          git fetch origin gh-pages
          mike delete main
          mike deploy --push main
